-- =====================================================================
-- V1 - Baseline dos cadastros do dominio
-- Modelagem baseada em conhecimento publico do setor cafeeiro
-- (classificacao COB por peneira/tipo/bebida) e em endereçamento
-- generico de armazem (armazem > rua > coluna > nivel).
-- =====================================================================

-- ---------------------------------------------------------------------
-- PRODUTOR
-- ---------------------------------------------------------------------
CREATE TABLE produtor (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo        VARCHAR(20)  NOT NULL,
    nome          VARCHAR(150) NOT NULL,
    municipio     VARCHAR(100),
    uf            CHAR(2),
    criado_em     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    atualizado_em TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version       BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT uk_produtor_codigo UNIQUE (codigo),
    CONSTRAINT ck_produtor_uf CHECK (uf IS NULL OR uf ~ '^[A-Z]{2}$')
);

COMMENT ON TABLE produtor IS 'Produtor/fornecedor de origem do lote de cafe';

-- ---------------------------------------------------------------------
-- ARMAZEM
-- ---------------------------------------------------------------------
CREATE TABLE armazem (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo        VARCHAR(10)  NOT NULL,
    nome          VARCHAR(120) NOT NULL,
    municipio     VARCHAR(100),
    uf            CHAR(2),
    ativo         BOOLEAN      NOT NULL DEFAULT TRUE,
    criado_em     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    atualizado_em TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version       BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT uk_armazem_codigo UNIQUE (codigo)
);

-- ---------------------------------------------------------------------
-- POSICAO (endereço fisico dentro do armazem)
-- ---------------------------------------------------------------------
CREATE TABLE posicao (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    armazem_id     BIGINT        NOT NULL,
    rua            VARCHAR(10)   NOT NULL,
    coluna         VARCHAR(10)   NOT NULL,
    nivel          VARCHAR(10)   NOT NULL,
    codigo         VARCHAR(40)   NOT NULL,   -- ex.: AR1-R03-C12-N2
    capacidade_kg  NUMERIC(12,3) NOT NULL,
    ativa          BOOLEAN       NOT NULL DEFAULT TRUE,
    criado_em      TIMESTAMPTZ   NOT NULL DEFAULT now(),
    atualizado_em  TIMESTAMPTZ   NOT NULL DEFAULT now(),
    version        BIGINT        NOT NULL DEFAULT 0,
    CONSTRAINT fk_posicao_armazem FOREIGN KEY (armazem_id) REFERENCES armazem (id),
    CONSTRAINT uk_posicao_codigo UNIQUE (codigo),
    CONSTRAINT uk_posicao_endereco UNIQUE (armazem_id, rua, coluna, nivel),
    CONSTRAINT ck_posicao_capacidade CHECK (capacidade_kg > 0)
);

CREATE INDEX ix_posicao_armazem ON posicao (armazem_id);

COMMENT ON COLUMN posicao.capacidade_kg IS
    'Capacidade maxima em kg. A ocupacao NAO e armazenada: e derivada do ledger de movimentacao.';

-- ---------------------------------------------------------------------
-- LOTE
-- ---------------------------------------------------------------------
CREATE TABLE lote (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo              VARCHAR(30)   NOT NULL,
    produtor_id         BIGINT        NOT NULL,
    safra               INTEGER       NOT NULL,
    peso_liquido_kg     NUMERIC(12,3) NOT NULL,
    sacas               INTEGER,
    umidade_percentual  NUMERIC(5,2),
    peneira             VARCHAR(10),   -- ex.: 17/18
    tipo                VARCHAR(10),   -- ex.: T6, T4/5 (classificacao por defeitos)
    bebida              VARCHAR(30),   -- ex.: DURA, RIADA, MOLE
    data_entrada        DATE          NOT NULL,
    status              VARCHAR(20)   NOT NULL DEFAULT 'AGUARDANDO_ALOCACAO',
    criado_em           TIMESTAMPTZ   NOT NULL DEFAULT now(),
    atualizado_em       TIMESTAMPTZ   NOT NULL DEFAULT now(),
    version             BIGINT        NOT NULL DEFAULT 0,
    CONSTRAINT fk_lote_produtor FOREIGN KEY (produtor_id) REFERENCES produtor (id),
    CONSTRAINT uk_lote_codigo UNIQUE (codigo),
    CONSTRAINT ck_lote_peso CHECK (peso_liquido_kg > 0),
    CONSTRAINT ck_lote_sacas CHECK (sacas IS NULL OR sacas > 0),
    CONSTRAINT ck_lote_safra CHECK (safra BETWEEN 1900 AND 2200),
    CONSTRAINT ck_lote_umidade CHECK (umidade_percentual IS NULL
                                      OR (umidade_percentual >= 0 AND umidade_percentual <= 100)),
    CONSTRAINT ck_lote_status CHECK (status IN (
        'AGUARDANDO_ALOCACAO',
        'ARMAZENADO',
        'RESERVADO',
        'EMBARCADO'
    ))
);

CREATE INDEX ix_lote_produtor ON lote (produtor_id);
CREATE INDEX ix_lote_status   ON lote (status);
CREATE INDEX ix_lote_safra    ON lote (safra);

COMMENT ON COLUMN lote.status IS
    'AGUARDANDO_ALOCACAO -> ARMAZENADO -> RESERVADO -> EMBARCADO (EMBARCADO e terminal)';
