-- =====================================================================
-- V1 - Baseline of the domain registry tables
-- Modeled from public knowledge of the coffee industry (COB
-- classification by screen size / defect type / cup quality) and from
-- generic warehouse addressing (warehouse > aisle > bay > level).
-- =====================================================================

-- ---------------------------------------------------------------------
-- PRODUCER
-- ---------------------------------------------------------------------
CREATE TABLE producer (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(20)  NOT NULL,
    name        VARCHAR(150) NOT NULL,
    city        VARCHAR(100),
    state       CHAR(2),
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version     BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT uk_producer_code UNIQUE (code),
    CONSTRAINT ck_producer_state CHECK (state IS NULL OR state ~ '^[A-Z]{2}$')
);

COMMENT ON TABLE producer IS 'Producer/supplier the coffee lot originates from';

-- ---------------------------------------------------------------------
-- WAREHOUSE
-- ---------------------------------------------------------------------
CREATE TABLE warehouse (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(10)  NOT NULL,
    name        VARCHAR(120) NOT NULL,
    city        VARCHAR(100),
    state       CHAR(2),
    active      BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version     BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT uk_warehouse_code UNIQUE (code)
);

-- ---------------------------------------------------------------------
-- STORAGE_POSITION (physical address inside the warehouse)
-- ---------------------------------------------------------------------
CREATE TABLE storage_position (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    warehouse_id  BIGINT        NOT NULL,
    aisle         VARCHAR(10)   NOT NULL,
    bay           VARCHAR(10)   NOT NULL,
    level         VARCHAR(10)   NOT NULL,
    code          VARCHAR(40)   NOT NULL,   -- e.g. WH1-A03-B12-L02
    capacity_kg   NUMERIC(12,3) NOT NULL,
    active        BOOLEAN       NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ   NOT NULL DEFAULT now(),
    version       BIGINT        NOT NULL DEFAULT 0,
    CONSTRAINT fk_storage_position_warehouse FOREIGN KEY (warehouse_id) REFERENCES warehouse (id),
    CONSTRAINT uk_storage_position_code UNIQUE (code),
    CONSTRAINT uk_storage_position_address UNIQUE (warehouse_id, aisle, bay, level),
    CONSTRAINT ck_storage_position_capacity CHECK (capacity_kg > 0)
);

CREATE INDEX ix_storage_position_warehouse ON storage_position (warehouse_id);

COMMENT ON COLUMN storage_position.capacity_kg IS
    'Maximum capacity in kg. Occupancy is NOT stored: it is derived from the movement ledger.';

-- ---------------------------------------------------------------------
-- LOT
-- ---------------------------------------------------------------------
CREATE TABLE lot (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code              VARCHAR(30)   NOT NULL,
    producer_id       BIGINT        NOT NULL,
    crop_year         INTEGER       NOT NULL,
    net_weight_kg     NUMERIC(12,3) NOT NULL,
    bags              INTEGER,
    moisture_percent  NUMERIC(5,2),
    screen_size       VARCHAR(10),   -- e.g. 17/18
    defect_type       VARCHAR(10),   -- e.g. T6, T4/5 (classification by defect count)
    cup_quality       VARCHAR(30),   -- e.g. HARD, RIOY, SOFT
    received_on       DATE          NOT NULL,
    status            VARCHAR(20)   NOT NULL DEFAULT 'AWAITING_ALLOCATION',
    created_at        TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ   NOT NULL DEFAULT now(),
    version           BIGINT        NOT NULL DEFAULT 0,
    CONSTRAINT fk_lot_producer FOREIGN KEY (producer_id) REFERENCES producer (id),
    CONSTRAINT uk_lot_code UNIQUE (code),
    CONSTRAINT ck_lot_net_weight CHECK (net_weight_kg > 0),
    CONSTRAINT ck_lot_bags CHECK (bags IS NULL OR bags > 0),
    CONSTRAINT ck_lot_crop_year CHECK (crop_year BETWEEN 1900 AND 2200),
    CONSTRAINT ck_lot_moisture CHECK (moisture_percent IS NULL
                                      OR (moisture_percent >= 0 AND moisture_percent <= 100)),
    CONSTRAINT ck_lot_status CHECK (status IN (
        'AWAITING_ALLOCATION',
        'STORED',
        'RESERVED',
        'SHIPPED'
    ))
);

CREATE INDEX ix_lot_producer  ON lot (producer_id);
CREATE INDEX ix_lot_status    ON lot (status);
CREATE INDEX ix_lot_crop_year ON lot (crop_year);

COMMENT ON COLUMN lot.status IS
    'AWAITING_ALLOCATION -> STORED -> RESERVED -> SHIPPED (SHIPPED is terminal)';
