-- =====================================================================
-- V2 - Movement ledger
--
-- Append-only by design: this table takes INSERTs and nothing else.
-- All position occupancy and all lot balances are aggregations over it,
-- never stored columns, so the two can never drift apart.
--
-- That is also why there is no updated_at and no version here: a row
-- that is never updated has nothing to version. The absence of those
-- columns is the append-only contract, stated in the schema itself.
-- =====================================================================

CREATE TABLE stock_movement (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type                VARCHAR(20)   NOT NULL,
    lot_id              BIGINT        NOT NULL,
    source_position_id  BIGINT,
    target_position_id  BIGINT,
    weight_kg           NUMERIC(12,3) NOT NULL,
    occurred_at         TIMESTAMPTZ   NOT NULL DEFAULT now(),
    reason              VARCHAR(200),
    created_at          TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CONSTRAINT fk_stock_movement_lot
        FOREIGN KEY (lot_id) REFERENCES lot (id),
    CONSTRAINT fk_stock_movement_source
        FOREIGN KEY (source_position_id) REFERENCES storage_position (id),
    CONSTRAINT fk_stock_movement_target
        FOREIGN KEY (target_position_id) REFERENCES storage_position (id),
    CONSTRAINT ck_stock_movement_type CHECK (type IN ('INBOUND', 'TRANSFER', 'OUTBOUND')),
    CONSTRAINT ck_stock_movement_weight CHECK (weight_kg > 0),
    -- Each type has exactly the endpoints it can have. Without this the
    -- balance aggregations would have to defend themselves against rows
    -- the domain should never have allowed in.
    CONSTRAINT ck_stock_movement_endpoints CHECK (
        (type = 'INBOUND'
            AND source_position_id IS NULL
            AND target_position_id IS NOT NULL)
        OR (type = 'TRANSFER'
            AND source_position_id IS NOT NULL
            AND target_position_id IS NOT NULL
            AND source_position_id <> target_position_id)
        OR (type = 'OUTBOUND'
            AND source_position_id IS NOT NULL
            AND target_position_id IS NULL)
    )
);

-- The aggregations are the hot path: balance of a lot, occupancy of a
-- position, and the statement of a lot in chronological order.
CREATE INDEX ix_stock_movement_lot    ON stock_movement (lot_id, occurred_at);
CREATE INDEX ix_stock_movement_source ON stock_movement (source_position_id);
CREATE INDEX ix_stock_movement_target ON stock_movement (target_position_id);

COMMENT ON TABLE stock_movement IS
    'Append-only movement ledger. Never UPDATE, never DELETE: balances are derived from it.';

COMMENT ON COLUMN stock_movement.occurred_at IS
    'When the movement happened in the warehouse, which is not necessarily when it was recorded.';
