-- =====================================================================
-- V3 - Shipment and its items
--
-- A shipment composes coffee from several lots and, once confirmed,
-- becomes the thing that drives it out of the warehouse. It writes to the
-- ledger through the same door every other movement uses; it does not get
-- one of its own.
--
-- There is no reserved_kg column here or on lot, for the same reason there
-- is no current_occupancy on storage_position. Weight spoken for is an
-- aggregation over the items of DRAFT shipments, exactly as occupancy is
-- an aggregation over stock_movement.
-- =====================================================================

CREATE TABLE shipment (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code                    VARCHAR(30)   NOT NULL,
    status                  VARCHAR(20)   NOT NULL DEFAULT 'DRAFT',
    destination             VARCHAR(150)  NOT NULL,
    scheduled_for           DATE,
    confirmed_at            TIMESTAMPTZ,
    -- Blend snapshot. Null until the shipment is confirmed; frozen from
    -- that moment on. See the comments below.
    blend_moisture_percent  NUMERIC(5,2),
    blend_weight_kg         NUMERIC(12,3),
    blend_moisture_basis_kg NUMERIC(12,3),
    created_at              TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at              TIMESTAMPTZ   NOT NULL DEFAULT now(),
    version                 BIGINT        NOT NULL DEFAULT 0,
    CONSTRAINT uk_shipment_code UNIQUE (code),
    CONSTRAINT ck_shipment_status CHECK (status IN ('DRAFT', 'CONFIRMED', 'CANCELLED')),
    CONSTRAINT ck_shipment_moisture CHECK (
        blend_moisture_percent IS NULL
        OR (blend_moisture_percent >= 0 AND blend_moisture_percent <= 100)
    ),
    -- confirmed_at exists exactly when the shipment is confirmed. Keeping
    -- the two in step in the schema means no row can claim to be confirmed
    -- without saying when.
    CONSTRAINT ck_shipment_confirmed_at CHECK (
        (status = 'CONFIRMED' AND confirmed_at IS NOT NULL)
        OR (status <> 'CONFIRMED' AND confirmed_at IS NULL)
    ),
    -- The blend snapshot follows the same rule. A confirmed shipment always
    -- knows the weight it went out with; its moisture may still be null,
    -- because moisture is optional on a lot and a blend of lots that were
    -- never graded has no average to report.
    CONSTRAINT ck_shipment_blend_snapshot CHECK (
        (status = 'CONFIRMED' AND blend_weight_kg IS NOT NULL)
        OR (status <> 'CONFIRMED'
            AND blend_weight_kg IS NULL
            AND blend_moisture_percent IS NULL
            AND blend_moisture_basis_kg IS NULL)
    )
);

CREATE INDEX ix_shipment_status ON shipment (status);

COMMENT ON TABLE shipment IS
    'A dispatch composed from several lots. DRAFT -> CONFIRMED or CANCELLED, both terminal.';

COMMENT ON COLUMN shipment.blend_moisture_percent IS
    'Moisture averaged weighted by weight, frozen at confirmation. Null while DRAFT: until then it is derived on read, because the lots it averages can still be re-graded.';

COMMENT ON COLUMN shipment.blend_moisture_basis_kg IS
    'The weight the moisture average actually covers. Lots with no moisture reading are excluded from the average, so this is not always the shipment total -- reporting it keeps the average from quietly lying about its own coverage.';

-- ---------------------------------------------------------------------
-- SHIPMENT_ITEM
--
-- One line is a picking instruction: this much of this lot, out of this
-- position. Naming the position here rather than resolving it at
-- confirmation is what makes confirmation deterministic and lets the
-- balance check reuse the per-(lot, position) query the ledger already has.
-- ---------------------------------------------------------------------
CREATE TABLE shipment_item (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shipment_id         BIGINT        NOT NULL,
    lot_id              BIGINT        NOT NULL,
    source_position_id  BIGINT        NOT NULL,
    weight_kg           NUMERIC(12,3) NOT NULL,
    created_at          TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ   NOT NULL DEFAULT now(),
    version             BIGINT        NOT NULL DEFAULT 0,
    CONSTRAINT fk_shipment_item_shipment
        FOREIGN KEY (shipment_id) REFERENCES shipment (id),
    CONSTRAINT fk_shipment_item_lot
        FOREIGN KEY (lot_id) REFERENCES lot (id),
    CONSTRAINT fk_shipment_item_source
        FOREIGN KEY (source_position_id) REFERENCES storage_position (id),
    -- The same lot out of the same position is one line, whose weight is
    -- edited. Two lines would split a single instruction in two and make
    -- the reservation aggregation harder to read for no gain.
    CONSTRAINT uk_shipment_item_line UNIQUE (shipment_id, lot_id, source_position_id),
    CONSTRAINT ck_shipment_item_weight CHECK (weight_kg > 0)
);

-- Composition of one shipment, and the reservation aggregation, which asks
-- how much of a lot is spoken for across every DRAFT shipment.
CREATE INDEX ix_shipment_item_shipment ON shipment_item (shipment_id);
CREATE INDEX ix_shipment_item_lot      ON shipment_item (lot_id, source_position_id);

COMMENT ON TABLE shipment_item IS
    'One picking instruction: this much of this lot, out of this position. Mutable only while the shipment is DRAFT.';
