-- =====================================================================
-- V5 - Application users
--
-- Phase 5 puts Spring Security in front of the API. The credentials it
-- checks live here rather than in application.yml: a username and a
-- password in configuration is a demo, not an authorization model, and
-- it cannot express that an operator may move stock while only an
-- administrator invents a warehouse.
--
-- Named app_user because USER is a reserved word in SQL -- the same
-- reason storage_position is not called position (see docs/DECISIONS.md,
-- D1). Avoiding the quoting is worth the prefix.
-- =====================================================================

CREATE TABLE app_user (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username       VARCHAR(60)  NOT NULL,
    -- BCrypt output is always exactly 60 characters. The column is wider
    -- so that changing the encoder later is a code decision rather than
    -- a migration, and the hash is never truncated silently if it is.
    password_hash  VARCHAR(100) NOT NULL,
    display_name   VARCHAR(150) NOT NULL,
    role           VARCHAR(20)  NOT NULL,
    -- Disabling a user has to be possible without deleting the row: the
    -- movements they recorded still point at a person who existed.
    active         BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version        BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT uk_app_user_username UNIQUE (username),
    -- The same shape every other enum in this schema uses: the database
    -- states the allowed values and the entity maps them as STRING, so
    -- the two cannot drift (LotStatus, ShipmentStatus, MovementType).
    CONSTRAINT ck_app_user_role CHECK (role IN ('ADMIN', 'OPERATOR')),
    CONSTRAINT ck_app_user_username CHECK (username ~ '^[a-z0-9._-]{3,60}$'),
    CONSTRAINT ck_app_user_password_hash CHECK (length(password_hash) >= 20)
);

COMMENT ON TABLE app_user IS
    'Account that authenticates against the API. The role decides what it may do, not merely that it may.';

COMMENT ON COLUMN app_user.password_hash IS
    'BCrypt hash. The plaintext is never stored, never logged and never returned by any endpoint.';

COMMENT ON COLUMN app_user.role IS
    'ADMIN maintains the registry; OPERATOR moves stock and composes shipments. Both read.';
